### ISSUE TITLE
Implement source mapping

### ISSUE THREAD

**Issue by nbaksalyar** [headcrab-rs/headcrab#100]
- Read source file locations from DWARF.
- Map addresses to lines in the source code (addr2line should be used for this).
- Read the source files and display the source code along with the line numbers at the current debugger location.

**Comment by blitzerr** [comment]
I can work on this

**Comment by blitzerr** [comment]
@nbaksalyar If you can add some mentoring notes to this, I would appreciate it.

**Comment by bjorn3** [comment]
There is already a function to read the source line called [`Dwarf::source_snippet`](https://github.com/headcrab-rs/headcrab/blob/ab758ff2f5b7d719dfc4c87065d1d76ce720b9aa/src/symbol/source.rs#L71-L79). It only shows a single line though, so you may want to copy it to the `repl` example as new command and adapt it to show more lines, line numbers and maybe even syntax highlighting.

You could also use https://github.com/bjorn3/pretty_backtrace/blob/c8a19b94f369a2edd9d58b07eb4310d2e0a2c991/src/display_frame.rs#L63-L117 as starting point for this. It also depends on 
https://github.com/bjorn3/pretty_backtrace/blob/c8a19b94f369a2edd9d58b07eb4310d2e0a2c991/src/syntax_highlight.rs for the syntax highlighting. It has line numbers, syntax highlighting and it dims all lines except for the current one. It also shows the current column with a `^`.

To also be able to view source for sysroot crates like libstd, you would also need to map files starting with `/rustc/` followed by a hash to the local path of the sysroot crates when the `rust-src` rustup component is installed. This could for example be done at https://github.com/headcrab-rs/headcrab/blob/ab758ff2f5b7d719dfc4c87065d1d76ce720b9aa/src/symbol/source.rs#L61-L64. See for example

https://github.com/bjorn3/pretty_backtrace/blob/c8a19b94f369a2edd9d58b07eb4310d2e0a2c991/src/display_frame.rs#L48-L61 and https://github.com/bjorn3/pretty_backtrace/blob/c8a19b94f369a2edd9d58b07eb4310d2e0a2c991/src/display_frame.rs#L71-L91

Due to changes in the sysroot source layout you would need to change https://github.com/bjorn3/pretty_backtrace/blob/c8a19b94f369a2edd9d58b07eb4310d2e0a2c991/src/display_frame.rs#L53 to I think `/lib/rustlib/library`.

**Comment by blitzerr** [comment]
Thanks a lot @bjorn3 I will take some time to digest this information and then get back (probably with more questions). :)
