### ISSUE TITLE
Support breakpoints on Linux

### ISSUE THREAD

**Issue by bjorn3** [headcrab-rs/headcrab#55]
This works by overwriting the breakpoint target with `0xcc` (`int3`) and when continuing removing the breakpoint, setting the ip 1 back stepping a single instruction and then setting the breakpoint again and continuing normally.

**Comment by Arthamys** [comment]
From what I gather, there is no in-tree support for breakpoints yet.

If it's possible, I'd like to work on this issue to get up and running on the project !

**Comment by bjorn3** [comment]
https://github.com/headcrab-rs/headcrab/pull/73 added hardware breakpoints, of which there can only be a limited count. It is also not yet wired to the repl example. As for software breakpoints I already had a start for breakpoints: https://github.com/bjorn3/headcrab/tree/please_pause_a_moment (last commit) It doesn't handle single stepping and faulting instructions at the place of the breakpoint yet. Feel free to base your work on it.

**Comment by theIDinside** [comment]
This *seems* fairly, reasonably simple. I've written *really stupid naive implementations* of this in C++ before. This project seems amazing and I feel incredibly too stupid to be able to pull it off, but I do like a challenge and this type of works intrigues me/is my passion to be able to do, but could perhaps use some guidance in order to pull it off. I'll check previous work by @bjorn3, otherwise, I'll try and hack and slash until something works, make a PR, and if the feature is ok, but code is terrible, we could work from there if that's ok?

**Comment by theIDinside** [comment]
This issue seems dead/fixed already.

**Comment by bjorn3** [comment]
Indeed. This was fixed by #108.
