### ISSUE TITLE
Implement vm_write for Linux

### ISSUE THREAD

**Issue by nbaksalyar** [headcrab-rs/headcrab#7]
The API can look similar to `ReadMemory` and `target.read()`.

This will probably require dealing with `PTRACE_POKE` for write-protected pages.
For pages with write permssions, we can use more efficient `process_vm_writev(2)`.

**Comment by theIDinside** [comment]
I'm looking to contribute to this project. *please* close the issues that are closed. I'm spending way too much time looking "oh this could be suitable for me, a green dev", delve through the PR stories just to find out it's been closed in a separate thread somewhere, kind of frustrating, especially since it consumes quite a bit of time.
